Repository panoratech/Panora, pull requests merged in 2024-06, with the labels that each got.

#490 :card_file_box: File_sharing (fs_) Unified Vertical
  packages/api/scripts/init.sql
  packages/api/scripts/seed.sql
Labels: important, backend, Core-Team

#484 feat:Add integration with Close CRM
  .env.example
  docker-compose.dev.yml
  packages/api/prisma/schema.prisma
  packages/api/scripts/init.sql
  packages/api/scripts/seed.sql
  packages/api/src/@core/connections/crm/crm.connection.module.ts
  packages/api/src/@core/connections/crm/services/close/close.service.ts
  packages/api/src/@core/project-connectors/project-connectors.controller.ts
  packages/api/src/@core/project-connectors/project-connectors.service.ts
  packages/api/src/@core/utils/types/original/original.crm.ts
  packages/api/src/crm/company/company.module.ts
  packages/api/src/crm/company/services/close/index.ts
  packages/api/src/crm/company/services/close/mappers.ts
  packages/api/src/crm/company/services/close/types.ts
  packages/api/src/crm/company/types/mappingsTypes.ts
  packages/api/src/crm/contact/contact.controller.ts
  packages/api/src/crm/contact/contact.module.ts
  packages/api/src/crm/contact/services/close/index.ts
  packages/api/src/crm/contact/services/close/mappers.ts
  packages/api/src/crm/contact/services/close/types.ts
  packages/api/src/crm/contact/types/mappingsTypes.ts
  packages/api/src/crm/deal/deal.module.ts
  packages/api/src/crm/deal/services/close/index.ts
  packages/api/src/crm/deal/services/close/mappers.ts
  packages/api/src/crm/deal/services/close/types.ts
  packages/api/src/crm/deal/types/mappingsTypes.ts
  packages/api/src/crm/engagement/engagement.module.ts
  packages/api/src/crm/engagement/services/close/index.ts
  packages/api/src/crm/engagement/services/close/mappers.ts
  packages/api/src/crm/engagement/services/close/types.ts
  packages/api/src/crm/engagement/sync/sync.service.ts
  packages/api/src/crm/engagement/types/mappingsTypes.ts
  packages/api/src/crm/note/note.module.ts
  packages/api/src/crm/note/services/close/index.ts
  packages/api/src/crm/note/services/close/mappers.ts
  packages/api/src/crm/note/services/close/types.ts
  packages/api/src/crm/note/types/mappingsTypes.ts
  packages/api/src/crm/stage/services/close/index.ts
  packages/api/src/crm/stage/services/close/mappers.ts
  packages/api/src/crm/stage/services/close/types.ts
  packages/api/src/crm/stage/stage.module.ts
  packages/api/src/crm/stage/types/mappingsTypes.ts
  packages/api/src/crm/task/services/close/index.ts
  packages/api/src/crm/task/services/close/mappers.ts
  packages/api/src/crm/task/services/close/types.ts
  packages/api/src/crm/task/task.module.ts
  packages/api/src/crm/task/types/mappingsTypes.ts
  packages/api/src/crm/user/services/close/index.ts
  packages/api/src/crm/user/services/close/mappers.ts
  packages/api/src/crm/user/services/close/types.ts
  packages/api/src/crm/user/types/mappingsTypes.ts
  packages/api/src/crm/user/user.module.ts
  packages/shared/src/authUrl.ts
  packages/shared/src/connectors/enum.ts
  packages/shared/src/connectors/index.ts
  packages/shared/src/connectors/metadata.ts
Labels: 🙋 Bounty claim

#505 :card_file_box: ATS DB Model + Updates on fs_ vertical
  docker-compose.dev.yml
  packages/api/scripts/init.sql
  packages/api/scripts/seed.sql
Labels: backend, Core-Team
